eureka:
  instance:
    preferIpAddress: false
    hostName: sampleservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck.enabled: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.kdzido.thesis.sample: DEBUG
