eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# TODO sensible defaults
security.oauth2.resource.userInfoUri: http://localhost:7999/auth/user

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.kdzido.thesis.sample: DEBUG
